image: node:latest
pipelines:
 branches:
   dev-mainnet:
     - step:
       services:
         - docker
       script:
         - yarn install
         - yarn build
         - pipe: atlassian/ftp-deploy:0.3.0 
           variables:
             USER: $ftp_user
             PASSWORD: $ftp_password
             SERVER: $ftp_host
             REMOTE_PATH: $ftp_remote_path
             LOCAL_PATH: $ftp_local_path #Optional
             #DEBUG: '<boolean>' # Optional
             #DELETE_FLAG: '<boolean>' # Optional. This is a option to delete old files before transferring new ones. Default: true.