import { http, createConfig } from "wagmi";
import {
  mainnet,
  sepolia,
  aurora,
  auroraTestnet,
  avalancheFuji,
  optimism,
  optimismSepolia,
  base,
  baseSepolia,
  arbitrum,
  arbitrumSepolia,
  polygon,
  polygonMumbai,
  optimismGoerli,
  cronosTestnet,
  cronos,
  filecoin,
  filecoinHyperspace,
} from "wagmi/chains";

export const config = createConfig({
  ssr: true,
  chains: [
    mainnet,
    sepolia,
    avalancheFuji,
    optimism,
    optimismSepolia,
    filecoin,
    filecoinHyperspace,
    base,
    baseSepolia,
    arbitrum,
    arbitrumSepolia,
    polygon,
    polygonMumbai,
    optimismGoerli,
    baseSepolia,
    arbitrumSepolia,
    cronos,
    cronosTestnet,
    polygonMumbai,
    aurora,
    auroraTestnet,
  ],
  transports: {
    [mainnet.id]: http(),
    [sepolia.id]: http(),
    [avalancheFuji.id]: http(),
    [optimism.id]: http(),
    [optimismSepolia.id]: http(),
    [base.id]: http(),
    [baseSepolia.id]: http(),
    [arbitrum.id]: http(),
    [arbitrumSepolia.id]: http(),
    [polygon.id]: http(),
    [polygonMumbai.id]: http(),
    [optimismGoerli.id]: http(),
    [aurora.id]: http(),
    [auroraTestnet.id]: http(),
    [cronos.id]: http(),
    [cronosTestnet.id]: http(),
    [filecoin.id]: http(),
    [filecoinHyperspace.id]: http(),
  },
});
