import type { NextPage } from 'next'
import Head from 'next/head'
import Nav from '../app/components/elements/Nav'
import Hero from '../app/components/elements/Hero'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="app">
      <Head>
        <title>Cryptea</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav />
        <Hero />
        <About />
        <Extras />
      </main>

      <footer>
        <Footer />

      </footer>
    </div>
  )
}

export default Home
