# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - run: yarn install
    - run: npm run build

    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:

          username: ${{ secrets.ftp_fusername }}
          server: ${{ secrets.ftp_host }}
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.ftp_secret }}


          # will put all file under this path
          local_path: ./.next/*
          # files will copy to under remote_path
          remote_path: /home/files/frontend/.next/

          # sftp args
          args: '-o ConnectTimeout=50'
